# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/CashierHistory.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cashier_history(object):
    def setupUi(self, cashier_history):
        cashier_history.setObjectName("cashier_history")
        cashier_history.resize(1599, 1023)
        cashier_history.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        cashier_history.setAutoFillBackground(False)
        cashier_history.setStyleSheet("QWidget#cashier_dashboard {\n"
"    background: #FEFEFE;\n"
"}")

        self.retranslateUi(cashier_history)
        QtCore.QMetaObject.connectSlotsByName(cashier_history)

    def retranslateUi(self, cashier_history):
        _translate = QtCore.QCoreApplication.translate
        cashier_history.setWindowTitle(_translate("cashier_history", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cashier_history = QtWidgets.QWidget()
    ui = Ui_cashier_history()
    ui.setupUi(cashier_history)
    cashier_history.show()
    sys.exit(app.exec())
