# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/cashierDashboard.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cashier_dashboard(object):
    def setupUi(self, cashier_dashboard):
        cashier_dashboard.setObjectName("cashier_dashboard")
        cashier_dashboard.resize(1600, 1034)
        self.items_list = QtWidgets.QScrollArea(parent=cashier_dashboard)
        self.items_list.setGeometry(QtCore.QRect(10, 10, 1021, 851))
        self.items_list.setWidgetResizable(True)
        self.items_list.setObjectName("items_list")
        self.list = QtWidgets.QWidget()
        self.list.setGeometry(QtCore.QRect(0, 0, 1019, 849))
        self.list.setObjectName("list")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.list)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_layout = QtWidgets.QVBoxLayout()
        self.list_layout.setObjectName("list_layout")
        self.verticalLayout.addLayout(self.list_layout)
        self.items_list.setWidget(self.list)
        self.pushButton = QtWidgets.QPushButton(parent=cashier_dashboard)
        self.pushButton.setGeometry(QtCore.QRect(20, 910, 271, 90))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=cashier_dashboard)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 910, 271, 90))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=cashier_dashboard)
        self.pushButton_3.setGeometry(QtCore.QRect(1180, 910, 361, 90))
        self.pushButton_3.setObjectName("pushButton_3")
        self.items_overview = QtWidgets.QScrollArea(parent=cashier_dashboard)
        self.items_overview.setGeometry(QtCore.QRect(1070, 10, 531, 851))
        self.items_overview.setWidgetResizable(True)
        self.items_overview.setObjectName("items_overview")
        self.receipt_area = QtWidgets.QWidget()
        self.receipt_area.setGeometry(QtCore.QRect(0, 0, 529, 849))
        self.receipt_area.setObjectName("receipt_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.receipt_area)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.receipt_layout = QtWidgets.QVBoxLayout()
        self.receipt_layout.setObjectName("receipt_layout")
        self.verticalLayout_2.addLayout(self.receipt_layout)
        self.items_overview.setWidget(self.receipt_area)

        self.retranslateUi(cashier_dashboard)
        QtCore.QMetaObject.connectSlotsByName(cashier_dashboard)

    def retranslateUi(self, cashier_dashboard):
        _translate = QtCore.QCoreApplication.translate
        cashier_dashboard.setWindowTitle(_translate("cashier_dashboard", "Form"))
        self.pushButton.setText(_translate("cashier_dashboard", "Void"))
        self.pushButton_2.setText(_translate("cashier_dashboard", "Discount"))
        self.pushButton_3.setText(_translate("cashier_dashboard", "PRINT RECEIPT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cashier_dashboard = QtWidgets.QWidget()
    ui = Ui_cashier_dashboard()
    ui.setupUi(cashier_dashboard)
    cashier_dashboard.show()
    sys.exit(app.exec())
