# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/salesForm.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_w_cashier(object):
    def setupUi(self, w_cashier):
        w_cashier.setObjectName("w_cashier")
        w_cashier.resize(1921, 1040)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/MINI-GRO.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        w_cashier.setWindowIcon(icon)
        self.gb_sidebar = QtWidgets.QGroupBox(parent=w_cashier)
        self.gb_sidebar.setGeometry(QtCore.QRect(40, 0, 231, 1040))
        self.gb_sidebar.setMinimumSize(QtCore.QSize(0, 1040))
        self.gb_sidebar.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-top-left-radius: 40px;\n"
"    border-bottom-left-radius: 40px;\n"
"}")
        self.gb_sidebar.setTitle("")
        self.gb_sidebar.setObjectName("gb_sidebar")
        self.layoutWidget = QtWidgets.QWidget(parent=self.gb_sidebar)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 231, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Logo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Logo.setMaximumSize(QtCore.QSize(229, 137))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/logo_u1.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.verticalLayout.addWidget(self.Logo)
        spacerItem = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.pb_dashboard = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_dashboard.setMinimumSize(QtCore.QSize(80, 80))
        self.pb_dashboard.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pb_dashboard.setObjectName("pb_dashboard")
        self.verticalLayout.addWidget(self.pb_dashboard)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pb_history = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_history.setMinimumSize(QtCore.QSize(80, 80))
        self.pb_history.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pb_history.setObjectName("pb_history")
        self.verticalLayout.addWidget(self.pb_history)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pb_report = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_report.setMinimumSize(QtCore.QSize(80, 80))
        self.pb_report.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pb_report.setObjectName("pb_report")
        self.verticalLayout.addWidget(self.pb_report)
        self.userPlaceholder = QtWidgets.QWidget(parent=self.gb_sidebar)
        self.userPlaceholder.setGeometry(QtCore.QRect(10, 670, 221, 311))
        self.userPlaceholder.setObjectName("userPlaceholder")
        self.sw_sales = QtWidgets.QStackedWidget(parent=w_cashier)
        self.sw_sales.setGeometry(QtCore.QRect(290, 0, 1600, 1040))
        self.sw_sales.setObjectName("sw_sales")

        self.retranslateUi(w_cashier)
        self.sw_sales.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(w_cashier)

    def retranslateUi(self, w_cashier):
        _translate = QtCore.QCoreApplication.translate
        w_cashier.setWindowTitle(_translate("w_cashier", "Form"))
        self.pb_dashboard.setText(_translate("w_cashier", "Transaction"))
        self.pb_history.setText(_translate("w_cashier", "History"))
        self.pb_report.setText(_translate("w_cashier", "Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w_cashier = QtWidgets.QWidget()
    ui = Ui_w_cashier()
    ui.setupUi(w_cashier)
    w_cashier.show()
    sys.exit(app.exec())
