# Form implementation generated from reading ui file 'C:/Users/abarq/PycharmProjects/POS-PY/src/frontend/ui/sales.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1300, 900)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 20, 1061, 861))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(390, 390, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.cashierImage = QtWidgets.QLabel(parent=Form)
        self.cashierImage.setGeometry(QtCore.QRect(50, 660, 100, 100))
        self.cashierImage.setObjectName("cashierImage")
        self.logoutButton = QtWidgets.QPushButton(parent=Form)
        self.logoutButton.setGeometry(QtCore.QRect(60, 820, 75, 24))
        self.logoutButton.setObjectName("logoutButton")
        self.setImage = QtWidgets.QPushButton(parent=Form)
        self.setImage.setGeometry(QtCore.QRect(60, 760, 75, 24))
        self.setImage.setObjectName("setImage")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "SALES"))
        self.cashierImage.setText(_translate("Form", "IMAGE PLACE HOLDER"))
        self.logoutButton.setText(_translate("Form", "Log out"))
        self.setImage.setText(_translate("Form", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
