# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/AccountEdit.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_account_popup(object):
    def setupUi(self, account_popup):
        account_popup.setObjectName("account_popup")
        account_popup.resize(971, 565)
        account_popup.setStyleSheet("QWidget#custom_modal {\n"
"    background-color: #FFFFFF;\n"
"    border: 4px solid rgba(29,33,41,1);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius:5px;\n"
"    border: 1px solid #5E5E5E;\n"
"    padding: 5px 5px;\n"
"}")
        self.pb_close = QtWidgets.QPushButton(parent=account_popup)
        self.pb_close.setGeometry(QtCore.QRect(930, 10, 30, 30))
        self.pb_close.setStyleSheet("QPushButton {\n"
"    background: #00000000;\n"
"    border: none;\n"
"}")
        self.pb_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/circle-xmark.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pb_close.setIcon(icon)
        self.pb_close.setIconSize(QtCore.QSize(30, 30))
        self.pb_close.setObjectName("pb_close")
        self.lb_userImg = QtWidgets.QLabel(parent=account_popup)
        self.lb_userImg.setGeometry(QtCore.QRect(100, 100, 211, 211))
        self.lb_userImg.setScaledContents(True)
        self.lb_userImg.setObjectName("lb_userImg")
        self.pb_img = QtWidgets.QPushButton(parent=account_popup)
        self.pb_img.setGeometry(QtCore.QRect(110, 330, 171, 51))
        self.pb_img.setObjectName("pb_img")
        self.le_username = QtWidgets.QLineEdit(parent=account_popup)
        self.le_username.setGeometry(QtCore.QRect(390, 270, 311, 22))
        self.le_username.setObjectName("le_username")
        self.lb_1 = QtWidgets.QLabel(parent=account_popup)
        self.lb_1.setGeometry(QtCore.QRect(390, 250, 71, 16))
        self.lb_1.setObjectName("lb_1")
        self.le_email = QtWidgets.QLineEdit(parent=account_popup)
        self.le_email.setGeometry(QtCore.QRect(390, 170, 311, 21))
        self.le_email.setObjectName("le_email")
        self.lb_3 = QtWidgets.QLabel(parent=account_popup)
        self.lb_3.setGeometry(QtCore.QRect(390, 150, 61, 16))
        self.lb_3.setObjectName("lb_3")
        self.lb_4 = QtWidgets.QLabel(parent=account_popup)
        self.lb_4.setGeometry(QtCore.QRect(560, 90, 81, 16))
        self.lb_4.setObjectName("lb_4")
        self.le_name = QtWidgets.QLineEdit(parent=account_popup)
        self.le_name.setGeometry(QtCore.QRect(562, 110, 141, 22))
        self.le_name.setText("")
        self.le_name.setObjectName("le_name")
        self.le_userId = QtWidgets.QLineEdit(parent=account_popup)
        self.le_userId.setGeometry(QtCore.QRect(390, 110, 131, 22))
        self.le_userId.setText("")
        self.le_userId.setObjectName("le_userId")
        self.lb_2 = QtWidgets.QLabel(parent=account_popup)
        self.lb_2.setGeometry(QtCore.QRect(390, 90, 61, 16))
        self.lb_2.setObjectName("lb_2")
        self.lb_action = QtWidgets.QLabel(parent=account_popup)
        self.lb_action.setGeometry(QtCore.QRect(50, 30, 71, 21))
        self.lb_action.setObjectName("lb_action")
        self.pb_save = QtWidgets.QPushButton(parent=account_popup)
        self.pb_save.setGeometry(QtCore.QRect(720, 430, 171, 51))
        self.pb_save.setObjectName("pb_save")
        self.le_password = QtWidgets.QLineEdit(parent=account_popup)
        self.le_password.setGeometry(QtCore.QRect(390, 320, 311, 22))
        self.le_password.setObjectName("le_password")
        self.lb_5 = QtWidgets.QLabel(parent=account_popup)
        self.lb_5.setGeometry(QtCore.QRect(390, 300, 71, 16))
        self.lb_5.setObjectName("lb_5")
        self.le_confirmPw = QtWidgets.QLineEdit(parent=account_popup)
        self.le_confirmPw.setGeometry(QtCore.QRect(390, 370, 311, 22))
        self.le_confirmPw.setObjectName("le_confirmPw")
        self.lb_6 = QtWidgets.QLabel(parent=account_popup)
        self.lb_6.setGeometry(QtCore.QRect(390, 350, 101, 16))
        self.lb_6.setObjectName("lb_6")
        self.le_phone = QtWidgets.QLineEdit(parent=account_popup)
        self.le_phone.setGeometry(QtCore.QRect(390, 220, 311, 22))
        self.le_phone.setObjectName("le_phone")
        self.lb_7 = QtWidgets.QLabel(parent=account_popup)
        self.lb_7.setGeometry(QtCore.QRect(390, 200, 71, 16))
        self.lb_7.setObjectName("lb_7")
        self.rb_true = QtWidgets.QRadioButton(parent=account_popup)
        self.rb_true.setGeometry(QtCore.QRect(770, 170, 89, 20))
        self.rb_true.setObjectName("rb_true")
        self.rb_bg = QtWidgets.QButtonGroup(account_popup)
        self.rb_bg.setObjectName("rb_bg")
        self.rb_bg.addButton(self.rb_true)
        self.rb_false = QtWidgets.QRadioButton(parent=account_popup)
        self.rb_false.setGeometry(QtCore.QRect(770, 200, 89, 20))
        self.rb_false.setObjectName("rb_false")
        self.rb_bg.addButton(self.rb_false)
        self.lb_2fa = QtWidgets.QLabel(parent=account_popup)
        self.lb_2fa.setGeometry(QtCore.QRect(770, 140, 91, 16))
        self.lb_2fa.setObjectName("lb_2fa")

        self.retranslateUi(account_popup)
        QtCore.QMetaObject.connectSlotsByName(account_popup)

    def retranslateUi(self, account_popup):
        _translate = QtCore.QCoreApplication.translate
        account_popup.setWindowTitle(_translate("account_popup", "Form"))
        self.lb_userImg.setText(_translate("account_popup", "Placeholder"))
        self.pb_img.setText(_translate("account_popup", "Select Image"))
        self.lb_1.setText(_translate("account_popup", "Username"))
        self.lb_3.setText(_translate("account_popup", "Email"))
        self.lb_4.setText(_translate("account_popup", "Name"))
        self.lb_2.setText(_translate("account_popup", "User Id"))
        self.lb_action.setText(_translate("account_popup", "Item Details"))
        self.pb_save.setText(_translate("account_popup", "Save"))
        self.lb_5.setText(_translate("account_popup", "Password"))
        self.lb_6.setText(_translate("account_popup", "Confirm Password"))
        self.lb_7.setText(_translate("account_popup", "Phone"))
        self.rb_true.setText(_translate("account_popup", "True"))
        self.rb_false.setText(_translate("account_popup", "False"))
        self.lb_2fa.setText(_translate("account_popup", "Two Factor Auth"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    account_popup = QtWidgets.QWidget()
    ui = Ui_account_popup()
    ui.setupUi(account_popup)
    account_popup.show()
    sys.exit(app.exec())
