# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/AdminHistory.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_admin_history(object):
    def setupUi(self, admin_history):
        admin_history.setObjectName("admin_history")
        admin_history.resize(1661, 1041)
        admin_history.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        admin_history.setAutoFillBackground(False)
        admin_history.setStyleSheet("QWidget#cashier_dashboard {\n"
"    background: #FEFEFE;\n"
"}")
        self.admin_MainContainer = QtWidgets.QGroupBox(parent=admin_history)
        self.admin_MainContainer.setGeometry(QtCore.QRect(0, 0, 1661, 1041))
        self.admin_MainContainer.setStyleSheet("QGroupBox#admin_MainContainer{\n"
"    background: #rgba(255,255,255,0.5);\n"
"}")
        self.admin_MainContainer.setTitle("")
        self.admin_MainContainer.setObjectName("admin_MainContainer")
        self.gb_container = QtWidgets.QGroupBox(parent=self.admin_MainContainer)
        self.gb_container.setGeometry(QtCore.QRect(10, 40, 1120, 900))
        self.gb_container.setStyleSheet("QGroupBox {\n"
"    background: rgba(248,249,250, 1);\n"
"    border: 3px solid rgba(29,33,40, 1);\n"
"    border-radius:13px;\n"
"}")
        self.gb_container.setTitle("")
        self.gb_container.setObjectName("gb_container")
        self.tv_history = QtWidgets.QTableView(parent=self.gb_container)
        self.tv_history.setGeometry(QtCore.QRect(19, 150, 1081, 720))
        self.tv_history.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tv_history.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tv_history.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.tv_history.setAlternatingRowColors(False)
        self.tv_history.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tv_history.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tv_history.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.tv_history.setShowGrid(False)
        self.tv_history.setSortingEnabled(True)
        self.tv_history.setObjectName("tv_history")
        self.tv_history.horizontalHeader().setDefaultSectionSize(300)
        self.tv_history.horizontalHeader().setMinimumSectionSize(0)
        self.lb_transaction = QtWidgets.QLabel(parent=self.gb_container)
        self.lb_transaction.setGeometry(QtCore.QRect(50, 40, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(28)
        font.setBold(True)
        self.lb_transaction.setFont(font)
        self.lb_transaction.setObjectName("lb_transaction")
        self.le_sort = QtWidgets.QLineEdit(parent=self.gb_container)
        self.le_sort.setGeometry(QtCore.QRect(290, 40, 500, 50))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.le_sort.setFont(font)
        self.le_sort.setStyleSheet("QLineEdit {\n"
"    background: rgba(255,255,255,1); /* white */\n"
"  border-radius: 25px; \n"
"  border-width: 3px; \n"
"  border-color: rgba(29,33,40,1); /* neutral-800 */\n"
"  border-style: solid; \n"
"}")
        self.le_sort.setText("")
        self.le_sort.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.le_sort.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
        self.le_sort.setObjectName("le_sort")
        self.receipt_placeholder = QtWidgets.QWidget(parent=self.admin_MainContainer)
        self.receipt_placeholder.setGeometry(QtCore.QRect(1180, 170, 360, 754))
        self.receipt_placeholder.setObjectName("receipt_placeholder")

        self.retranslateUi(admin_history)
        QtCore.QMetaObject.connectSlotsByName(admin_history)

    def retranslateUi(self, admin_history):
        _translate = QtCore.QCoreApplication.translate
        admin_history.setWindowTitle(_translate("admin_history", "Form"))
        self.lb_transaction.setText(_translate("admin_history", "Transaction"))
        self.le_sort.setPlaceholderText(_translate("admin_history", "Search Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin_history = QtWidgets.QWidget()
    ui = Ui_admin_history()
    ui.setupUi(admin_history)
    admin_history.show()
    sys.exit(app.exec())
