# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/AdminReports.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_admin_reports(object):
    def setupUi(self, admin_reports):
        admin_reports.setObjectName("admin_reports")
        admin_reports.resize(1661, 1041)
        admin_reports.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        admin_reports.setAutoFillBackground(False)
        admin_reports.setStyleSheet("QWidget#cashier_dashboard {\n"
"    background: #FEFEFE;\n"
"}")
        self.admin_MainContainer = QtWidgets.QGroupBox(parent=admin_reports)
        self.admin_MainContainer.setGeometry(QtCore.QRect(0, 0, 1661, 1041))
        self.admin_MainContainer.setStyleSheet("QGroupBox#admin_MainContainer{\n"
"    background: #rgba(255,255,255,0.5);\n"
"}")
        self.admin_MainContainer.setTitle("")
        self.admin_MainContainer.setObjectName("admin_MainContainer")
        self.gb_LineChart = QtWidgets.QGroupBox(parent=self.admin_MainContainer)
        self.gb_LineChart.setGeometry(QtCore.QRect(30, 300, 1171, 661))
        self.gb_LineChart.setStyleSheet("QGroupBox {\n"
"      background: rgba(243,244,246,1); /* neutral-200 */\n"
"  border-radius: 8px; /* border-xl */\n"
"  border-width: 3px; \n"
"  border-color: rgba(29,33,40,1); /* neutral-800 */\n"
"  border-style: solid; \n"
"  box-shadow: 0px 17px 35px rgba(243, 244, 246, 0.24), 0px 0px 2px rgba(243, 244, 246, 0.12); /* shadow-xl */\n"
"}")
        self.gb_LineChart.setTitle("")
        self.gb_LineChart.setObjectName("gb_LineChart")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.gb_LineChart)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 80, 1111, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_linechart = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_linechart.setContentsMargins(0, 0, 0, 0)
        self.layout_linechart.setObjectName("layout_linechart")
        self.label_5 = QtWidgets.QLabel(parent=self.gb_LineChart)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cb_linechart = QtWidgets.QComboBox(parent=self.gb_LineChart)
        self.cb_linechart.setGeometry(QtCore.QRect(990, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        self.cb_linechart.setFont(font)
        self.cb_linechart.setStyleSheet("QComboBox {\n"
"  font-family: Inter; \n"
"  font-size: 16px; \n"
"  color: rgba(23,26,31,1); \n"
"  background: rgba(243,244,246,1);\n"
"    border-radius: 8px;\n"
"    border: 2px solid rgba(50, 50,50, 0.7)\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}")
        self.cb_linechart.setObjectName("cb_linechart")
        self.layoutWidget = QtWidgets.QWidget(parent=self.admin_MainContainer)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 1591, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_Monthly = QtWidgets.QGroupBox(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Monthly.sizePolicy().hasHeightForWidth())
        self.gb_Monthly.setSizePolicy(sizePolicy)
        self.gb_Monthly.setMinimumSize(QtCore.QSize(341, 150))
        self.gb_Monthly.setMaximumSize(QtCore.QSize(341, 150))
        self.gb_Monthly.setStyleSheet("QGroupBox {  background: rgba(243,244,246,1); /* neutral-200 */\n"
"  border-radius: 8px; /* border-xl */\n"
"  border-width: 3px; \n"
"  border-color: rgba(29,33,40,1); /* neutral-800 */\n"
"  border-style: solid; \n"
"  box-shadow: 0px 17px 35px rgba(243, 244, 246, 0.24), 0px 0px 2px rgba(243, 244, 246, 0.12); /* shadow-xl */}")
        self.gb_Monthly.setTitle("")
        self.gb_Monthly.setObjectName("gb_Monthly")
        self.label_monthly = QtWidgets.QLabel(parent=self.gb_Monthly)
        self.label_monthly.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        font.setBold(True)
        self.label_monthly.setFont(font)
        self.label_monthly.setObjectName("label_monthly")
        self.lb_monthly = QtWidgets.QLabel(parent=self.gb_Monthly)
        self.lb_monthly.setGeometry(QtCore.QRect(60, 70, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(34)
        font.setBold(True)
        self.lb_monthly.setFont(font)
        self.lb_monthly.setObjectName("lb_monthly")
        self.peso = QtWidgets.QLabel(parent=self.gb_Monthly)
        self.peso.setGeometry(QtCore.QRect(10, 80, 41, 41))
        self.peso.setText("")
        self.peso.setPixmap(QtGui.QPixmap("./src/frontend/__image/peso-sign.svg"))
        self.peso.setScaledContents(True)
        self.peso.setObjectName("peso")
        self.label = QtWidgets.QLabel(parent=self.gb_Monthly)
        self.label.setGeometry(QtCore.QRect(220, 20, 100, 100))
        self.label.setStyleSheet("QLabel {\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "./src/frontend/__image/admin_elements/reports/photo_6156872775034322209_m.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.gb_Monthly)
        self.gb_Weekly = QtWidgets.QGroupBox(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Weekly.sizePolicy().hasHeightForWidth())
        self.gb_Weekly.setSizePolicy(sizePolicy)
        self.gb_Weekly.setMinimumSize(QtCore.QSize(341, 150))
        self.gb_Weekly.setMaximumSize(QtCore.QSize(341, 150))
        self.gb_Weekly.setStyleSheet("QGroupBox {  background: rgba(243,244,246,1); /* neutral-200 */\n"
"  border-radius: 8px; /* border-xl */\n"
"  border-width: 3px; \n"
"  border-color: rgba(29,33,40,1); /* neutral-800 */\n"
"  border-style: solid; \n"
"  box-shadow: 0px 17px 35px rgba(243, 244, 246, 0.24), 0px 0px 2px rgba(243, 244, 246, 0.12); /* shadow-xl */}")
        self.gb_Weekly.setTitle("")
        self.gb_Weekly.setObjectName("gb_Weekly")
        self.peso_2 = QtWidgets.QLabel(parent=self.gb_Weekly)
        self.peso_2.setGeometry(QtCore.QRect(10, 80, 41, 41))
        self.peso_2.setText("")
        self.peso_2.setPixmap(QtGui.QPixmap("./src/frontend/__image/peso-sign.svg"))
        self.peso_2.setScaledContents(True)
        self.peso_2.setObjectName("peso_2")
        self.lb_weekly = QtWidgets.QLabel(parent=self.gb_Weekly)
        self.lb_weekly.setGeometry(QtCore.QRect(60, 70, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(34)
        font.setBold(True)
        self.lb_weekly.setFont(font)
        self.lb_weekly.setObjectName("lb_weekly")
        self.label_weekly = QtWidgets.QLabel(parent=self.gb_Weekly)
        self.label_weekly.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        font.setBold(True)
        self.label_weekly.setFont(font)
        self.label_weekly.setObjectName("label_weekly")
        self.label_2 = QtWidgets.QLabel(parent=self.gb_Weekly)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 100, 100))
        self.label_2.setStyleSheet("QLabel {\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(
            "./src/frontend/__image/admin_elements/reports/photo_6156872775034322207_m.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.gb_Weekly)
        self.gb_Daily = QtWidgets.QGroupBox(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Daily.sizePolicy().hasHeightForWidth())
        self.gb_Daily.setSizePolicy(sizePolicy)
        self.gb_Daily.setMinimumSize(QtCore.QSize(341, 150))
        self.gb_Daily.setMaximumSize(QtCore.QSize(341, 150))
        self.gb_Daily.setStyleSheet("QGroupBox {  background: rgba(243,244,246,1); /* neutral-200 */\n"
"  border-radius: 8px; /* border-xl */\n"
"  border-width: 3px; \n"
"  border-color: rgba(29,33,40,1); /* neutral-800 */\n"
"  border-style: solid; \n"
"  box-shadow: 0px 17px 35px rgba(243, 244, 246, 0.24), 0px 0px 2px rgba(243, 244, 246, 0.12); /* shadow-xl */}")
        self.gb_Daily.setTitle("")
        self.gb_Daily.setObjectName("gb_Daily")
        self.peso_3 = QtWidgets.QLabel(parent=self.gb_Daily)
        self.peso_3.setGeometry(QtCore.QRect(10, 80, 41, 41))
        self.peso_3.setText("")
        self.peso_3.setPixmap(QtGui.QPixmap("./src/frontend/__image/peso-sign.svg"))
        self.peso_3.setScaledContents(True)
        self.peso_3.setObjectName("peso_3")
        self.lb_daily = QtWidgets.QLabel(parent=self.gb_Daily)
        self.lb_daily.setGeometry(QtCore.QRect(60, 70, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(34)
        font.setBold(True)
        self.lb_daily.setFont(font)
        self.lb_daily.setObjectName("lb_daily")
        self.label_daily = QtWidgets.QLabel(parent=self.gb_Daily)
        self.label_daily.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        font.setBold(True)
        self.label_daily.setFont(font)
        self.label_daily.setObjectName("label_daily")
        self.label_3 = QtWidgets.QLabel(parent=self.gb_Daily)
        self.label_3.setGeometry(QtCore.QRect(230, 20, 100, 100))
        self.label_3.setStyleSheet("QLabel {\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(
            "./src/frontend/__image/admin_elements/reports/photo_6156872775034322208_m.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.gb_Daily)
        self.gb_Annual = QtWidgets.QGroupBox(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Annual.sizePolicy().hasHeightForWidth())
        self.gb_Annual.setSizePolicy(sizePolicy)
        self.gb_Annual.setMinimumSize(QtCore.QSize(341, 150))
        self.gb_Annual.setMaximumSize(QtCore.QSize(341, 150))
        self.gb_Annual.setStyleSheet("QGroupBox {  background: rgba(243,244,246,1); /* neutral-200 */\n"
"  border-radius: 8px; /* border-xl */\n"
"  border-width: 3px; \n"
"  border-color: rgba(29,33,40,1); /* neutral-800 */\n"
"  border-style: solid; \n"
"  box-shadow: 0px 17px 35px rgba(243, 244, 246, 0.24), 0px 0px 2px rgba(243, 244, 246, 0.12); /* shadow-xl */}")
        self.gb_Annual.setTitle("")
        self.gb_Annual.setObjectName("gb_Annual")
        self.peso_4 = QtWidgets.QLabel(parent=self.gb_Annual)
        self.peso_4.setGeometry(QtCore.QRect(10, 80, 41, 41))
        self.peso_4.setText("")
        self.peso_4.setPixmap(QtGui.QPixmap("./src/frontend/__image/peso-sign.svg"))
        self.peso_4.setScaledContents(True)
        self.peso_4.setObjectName("peso_4")
        self.lb_annual = QtWidgets.QLabel(parent=self.gb_Annual)
        self.lb_annual.setGeometry(QtCore.QRect(60, 70, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(34)
        font.setBold(True)
        self.lb_annual.setFont(font)
        self.lb_annual.setObjectName("lb_annual")
        self.label_annual = QtWidgets.QLabel(parent=self.gb_Annual)
        self.label_annual.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        font.setBold(True)
        self.label_annual.setFont(font)
        self.label_annual.setObjectName("label_annual")
        self.label_4 = QtWidgets.QLabel(parent=self.gb_Annual)
        self.label_4.setGeometry(QtCore.QRect(230, 20, 100, 100))
        self.label_4.setStyleSheet("QLabel {\n"
"    background: rgba(0,0,0,0);\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(
            "./src/frontend/__image/admin_elements/reports/photo_6156872775034322210_m.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.gb_Annual)
        self.gb_PieChart = QtWidgets.QGroupBox(parent=self.admin_MainContainer)
        self.gb_PieChart.setGeometry(QtCore.QRect(1230, 300, 411, 481))
        self.gb_PieChart.setStyleSheet("QGroupBox {\n"
"      background: rgba(243,244,246,1); /* neutral-200 */\n"
"  border-radius: 6px; /* border-l */\n"
"  box-shadow: 0px 17px 35px rgba(23, 26, 31, 0.24), 0px 0px 2px rgba(23, 26, 31, 0.12); /* shadow-xl */\n"
"}")
        self.gb_PieChart.setTitle("")
        self.gb_PieChart.setObjectName("gb_PieChart")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.gb_PieChart)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 391, 421))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_piechart = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_piechart.setContentsMargins(0, 0, 0, 0)
        self.layout_piechart.setObjectName("layout_piechart")
        self.label_6 = QtWidgets.QLabel(parent=self.gb_PieChart)
        self.label_6.setGeometry(QtCore.QRect(0, 5, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QGroupBox {\n"
"      background: rgba(243,244,246,1); /* neutral-200 */\n"
"  border-radius: 6px; /* border-l */\n"
"  box-shadow: 0px 17px 35px rgba(23, 26, 31, 0.24), 0px 0px 2px rgba(23, 26, 31, 0.12); /* shadow-xl */\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.admin_MainContainer)
        self.label_7.setGeometry(QtCore.QRect(890, 190, 491, 461))
        self.label_7.setMinimumSize(QtCore.QSize(1, 0))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("./src/frontend/__image/admin_elements/reports/img2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.admin_MainContainer)
        self.label_8.setGeometry(QtCore.QRect(-110, 700, 491, 461))
        self.label_8.setMinimumSize(QtCore.QSize(1, 0))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("./src/frontend/__image/admin_elements/reports/img.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.label_7.raise_()
        self.gb_LineChart.raise_()
        self.layoutWidget.raise_()
        self.gb_PieChart.raise_()

        self.retranslateUi(admin_reports)
        QtCore.QMetaObject.connectSlotsByName(admin_reports)

    def retranslateUi(self, admin_reports):
        _translate = QtCore.QCoreApplication.translate
        admin_reports.setWindowTitle(_translate("admin_reports", "Form"))
        self.label_5.setText(_translate("admin_reports", "Sales Statistics"))
        self.label_monthly.setText(_translate("admin_reports", "Monthly Sales"))
        self.lb_monthly.setText(_translate("admin_reports", "10.5k"))
        self.lb_weekly.setText(_translate("admin_reports", "10.5k"))
        self.label_weekly.setText(_translate("admin_reports", "Weekly Sales"))
        self.lb_daily.setText(_translate("admin_reports", "10.50"))
        self.label_daily.setText(_translate("admin_reports", "Daily Sales"))
        self.lb_annual.setText(_translate("admin_reports", "10.5k"))
        self.label_annual.setText(_translate("admin_reports", "Annual Sales"))
        self.label_6.setText(_translate("admin_reports", "Top Selling Categories"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin_reports = QtWidgets.QWidget()
    ui = Ui_admin_reports()
    ui.setupUi(admin_reports)
    admin_reports.show()
    sys.exit(app.exec())
