# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/AdminAccounts.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_admin_accounts(object):
    def setupUi(self, admin_accounts):
        admin_accounts.setObjectName("admin_accounts")
        admin_accounts.resize(1661, 1041)
        admin_accounts.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        admin_accounts.setAutoFillBackground(False)
        admin_accounts.setStyleSheet("QWidget#cashier_dashboard {\n"
"    background: #FEFEFE;\n"
"}")
        self.admin_MainContainer = QtWidgets.QGroupBox(parent=admin_accounts)
        self.admin_MainContainer.setGeometry(QtCore.QRect(0, 0, 1661, 1041))
        self.admin_MainContainer.setStyleSheet("QGroupBox#admin_MainContainer{\n"
"    background: #rgba(255,255,255,0.5);\n"
"}")
        self.admin_MainContainer.setTitle("")
        self.admin_MainContainer.setObjectName("admin_MainContainer")
        self.gb_container = QtWidgets.QGroupBox(parent=self.admin_MainContainer)
        self.gb_container.setGeometry(QtCore.QRect(70, 40, 1521, 971))
        self.gb_container.setTitle("")
        self.gb_container.setObjectName("gb_container")
        self.tv_accounts = QtWidgets.QTableView(parent=self.gb_container)
        self.tv_accounts.setGeometry(QtCore.QRect(520, 120, 960, 720))
        self.tv_accounts.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tv_accounts.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tv_accounts.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.tv_accounts.setAlternatingRowColors(False)
        self.tv_accounts.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tv_accounts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tv_accounts.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.tv_accounts.setShowGrid(False)
        self.tv_accounts.setSortingEnabled(True)
        self.tv_accounts.setObjectName("tv_accounts")
        self.tv_accounts.horizontalHeader().setDefaultSectionSize(300)
        self.tv_accounts.horizontalHeader().setMinimumSectionSize(0)
        self.gb_cashier_details = QtWidgets.QGroupBox(parent=self.gb_container)
        self.gb_cashier_details.setGeometry(QtCore.QRect(60, 150, 361, 541))
        self.gb_cashier_details.setTitle("")
        self.gb_cashier_details.setObjectName("gb_cashier_details")
        self.lb_img = QtWidgets.QLabel(parent=self.gb_cashier_details)
        self.lb_img.setGeometry(QtCore.QRect(100, 80, 171, 171))
        self.lb_img.setScaledContents(True)
        self.lb_img.setObjectName("lb_img")
        self.lb_role = QtWidgets.QLabel(parent=self.gb_cashier_details)
        self.lb_role.setGeometry(QtCore.QRect(90, 360, 141, 31))
        self.lb_role.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_role.setObjectName("lb_role")
        self.pb_edit = QtWidgets.QPushButton(parent=self.gb_cashier_details)
        self.pb_edit.setGeometry(QtCore.QRect(120, 430, 75, 24))
        self.pb_edit.setObjectName("pb_edit")
        self.lb_name = QtWidgets.QLabel(parent=self.gb_cashier_details)
        self.lb_name.setGeometry(QtCore.QRect(90, 320, 141, 31))
        self.lb_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_name.setObjectName("lb_name")
        self.pb_add = QtWidgets.QPushButton(parent=self.gb_container)
        self.pb_add.setGeometry(QtCore.QRect(120, 740, 75, 24))
        self.pb_add.setObjectName("pb_add")
        self.pb_remove = QtWidgets.QPushButton(parent=self.gb_container)
        self.pb_remove.setGeometry(QtCore.QRect(280, 740, 75, 24))
        self.pb_remove.setObjectName("pb_remove")

        self.retranslateUi(admin_accounts)
        QtCore.QMetaObject.connectSlotsByName(admin_accounts)

    def retranslateUi(self, admin_accounts):
        _translate = QtCore.QCoreApplication.translate
        admin_accounts.setWindowTitle(_translate("admin_accounts", "Form"))
        self.lb_img.setText(_translate("admin_accounts", "TextLabel"))
        self.lb_role.setText(_translate("admin_accounts", "Role"))
        self.pb_edit.setText(_translate("admin_accounts", "Edit"))
        self.lb_name.setText(_translate("admin_accounts", "Name"))
        self.pb_add.setText(_translate("admin_accounts", "Add"))
        self.pb_remove.setText(_translate("admin_accounts", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin_accounts = QtWidgets.QWidget()
    ui = Ui_admin_accounts()
    ui.setupUi(admin_accounts)
    admin_accounts.show()
    sys.exit(app.exec())
