# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/loginForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(1920, 1040)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_form.sizePolicy().hasHeightForWidth())
        login_form.setSizePolicy(sizePolicy)
        login_form.setMinimumSize(QtCore.QSize(500, 400))
        login_form.setStyleSheet("QForm {\n"
"    background: #FEFEFE;\n"
"}")
        self.gb_banner_logo = QtWidgets.QGroupBox(parent=login_form)
        self.gb_banner_logo.setGeometry(QtCore.QRect(0, 0, 1031, 1041))
        self.gb_banner_logo.setStyleSheet("QGroupBox {\n"
"    border:  #00000000;\n"
"}")
        self.gb_banner_logo.setTitle("")
        self.gb_banner_logo.setObjectName("gb_banner_logo")
        self.lb_logo = QtWidgets.QLabel(parent=self.gb_banner_logo)
        self.lb_logo.setGeometry(QtCore.QRect(160, 260, 711, 441))
        self.lb_logo.setStyleSheet("")
        self.lb_logo.setText("")
        self.lb_logo.setPixmap(QtGui.QPixmap("./src/frontend/__image/logo_u1.png"))
        self.lb_logo.setScaledContents(True)
        self.lb_logo.setObjectName("lb_logo")
        self.lb_sys = QtWidgets.QLabel(parent=self.gb_banner_logo)
        self.lb_sys.setGeometry(QtCore.QRect(150, 30, 721, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.lb_sys.setFont(font)
        self.lb_sys.setStyleSheet("QLabel {\n"
"    color : #030E0A;\n"
"    background: #F8F9FAFF;\n"
"    border: 1px solid;\n"
"    border-radius:25px;\n"
"    border-color:#00000000;\n"
"}")
        self.lb_sys.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_sys.setObjectName("lb_sys")
        self.gb_form = QtWidgets.QGroupBox(parent=login_form)
        self.gb_form.setGeometry(QtCore.QRect(1150, 180, 637, 671))
        self.gb_form.setStyleSheet("QGroupBox {\n"
"    background: #FEFEFE;\n"
"    border-radius:8px;\n"
"    border: 3px solid #FF7FDF;\n"
"}\n"
"\n"
"QWidget#w_username, QWidget#w_password {\n"
"    background:#F3F4F6;\n"
"    border: #00000000;\n"
"    border-radius: 8px;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QLineEdit#le_pass, QLineEdit#le_username {\n"
"    background:#00000000;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#pb_logIn {\n"
"    background: #FF7FDF;\n"
"    border: none;\n"
"    border-radius:8px;\n"
"    color:white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: 5E5E5E;\n"
"    background-color:#2E2E2E;\n"
"}\n"
"\n"
"QCheckBox:indicator {\n"
"    border: 2px solid #f000b4;\n"
"    border-radius: 8px;\n"
"}")
        self.gb_form.setTitle("")
        self.gb_form.setObjectName("gb_form")
        self.label_5 = QtWidgets.QLabel(parent=self.gb_form)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(32)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #171A1F;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.gb_form)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: #9095A0;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.pb_logIn = QtWidgets.QPushButton(parent=self.gb_form)
        self.pb_logIn.setGeometry(QtCore.QRect(30, 410, 571, 44))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        font.setBold(True)
        self.pb_logIn.setFont(font)
        self.pb_logIn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pb_logIn.setObjectName("pb_logIn")
        self.layoutWidget = QtWidgets.QWidget(parent=self.gb_form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 370, 571, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.pb_forgotpw = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_forgotpw.sizePolicy().hasHeightForWidth())
        self.pb_forgotpw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(False)
        self.pb_forgotpw.setFont(font)
        self.pb_forgotpw.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pb_forgotpw.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pb_forgotpw.setStyleSheet("QPushButton {\n"
"    background: #00000000;\n"
"    color: #E845BF;\n"
"}")
        self.pb_forgotpw.setObjectName("pb_forgotpw")
        self.horizontalLayout.addWidget(self.pb_forgotpw)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.gb_form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 230, 571, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_username = QtWidgets.QWidget(parent=self.layoutWidget1)
        self.w_username.setMaximumSize(QtCore.QSize(16777215, 44))
        self.w_username.setObjectName("w_username")
        self.le_username = QtWidgets.QLineEdit(parent=self.w_username)
        self.le_username.setGeometry(QtCore.QRect(40, 0, 520, 44))
        self.le_username.setObjectName("le_username")
        self.label = QtWidgets.QLabel(parent=self.w_username)
        self.label.setGeometry(QtCore.QRect(10, 10, 25, 25))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./src/frontend/__image/login_elements/user.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.w_username)
        self.w_password = QtWidgets.QWidget(parent=self.layoutWidget1)
        self.w_password.setMaximumSize(QtCore.QSize(570, 44))
        self.w_password.setObjectName("w_password")
        self.le_pass = QtWidgets.QLineEdit(parent=self.w_password)
        self.le_pass.setGeometry(QtCore.QRect(40, 0, 520, 44))
        self.le_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_pass.setObjectName("le_pass")
        self.label_2 = QtWidgets.QLabel(parent=self.w_password)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 25, 25))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./src/frontend/__image/login_elements/lock.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.w_password)
        self.le_status = QtWidgets.QLabel(parent=self.gb_form)
        self.le_status.setGeometry(QtCore.QRect(30, 190, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.le_status.setFont(font)
        self.le_status.setStyleSheet("QLabel {\n"
"    color: #c40027;\n"
"}")
        self.le_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_status.setObjectName("le_status")
        self.element1 = QtWidgets.QLabel(parent=login_form)
        self.element1.setGeometry(QtCore.QRect(1330, -90, 701, 741))
        self.element1.setText("")
        self.element1.setPixmap(QtGui.QPixmap("./src/frontend/__image/login_elements/Image 49.png"))
        self.element1.setScaledContents(True)
        self.element1.setObjectName("element1")
        self.element2 = QtWidgets.QLabel(parent=login_form)
        self.element2.setGeometry(QtCore.QRect(990, 370, 671, 751))
        self.element2.setText("")
        self.element2.setPixmap(QtGui.QPixmap("./src/frontend/__image/login_elements/Image 51.png"))
        self.element2.setScaledContents(True)
        self.element2.setObjectName("element2")
        self.element2.raise_()
        self.element1.raise_()
        self.gb_banner_logo.raise_()
        self.gb_form.raise_()

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)
        login_form.setTabOrder(self.le_username, self.le_pass)
        login_form.setTabOrder(self.le_pass, self.checkBox)
        login_form.setTabOrder(self.checkBox, self.pb_forgotpw)
        login_form.setTabOrder(self.pb_forgotpw, self.pb_logIn)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Form"))
        self.lb_sys.setText(_translate("login_form", "Point Of Sale System"))
        self.label_5.setText(_translate("login_form", "Welcome Back"))
        self.label_6.setText(_translate("login_form", "Log in your account"))
        self.pb_logIn.setText(_translate("login_form", "Login"))
        self.checkBox.setText(_translate("login_form", "Remember Me"))
        self.pb_forgotpw.setText(_translate("login_form", "Forgot Password?"))
        self.le_username.setPlaceholderText(_translate("login_form", "Username"))
        self.le_pass.setPlaceholderText(_translate("login_form", "Password"))
        self.le_status.setText(_translate("login_form", "Wrong Password!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_form = QtWidgets.QWidget()
    ui = Ui_login_form()
    ui.setupUi(login_form)
    login_form.show()
    sys.exit(app.exec())
