# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/otpForm.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OTP(object):
    def setupUi(self, OTP):
        OTP.setObjectName("OTP")
        OTP.resize(1920, 1040)
        OTP.setStyleSheet("QWidget#OTP, QGroupBox#gb_container {\n"
"    background-color: #FFE5F8;\n"
"}")
        self.gb_container = QtWidgets.QGroupBox(parent=OTP)
        self.gb_container.setGeometry(QtCore.QRect(0, 0, 1921, 1041))
        self.gb_container.setTitle("")
        self.gb_container.setObjectName("gb_container")
        self.gb_twofacauth = QtWidgets.QGroupBox(parent=self.gb_container)
        self.gb_twofacauth.setGeometry(QtCore.QRect(662, 230, 596, 560))
        self.gb_twofacauth.setMaximumSize(QtCore.QSize(596, 560))
        self.gb_twofacauth.setStyleSheet("QGroupBox {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #ffd4f4;\n"
"    border: none;\n"
"    border-radius: 26px;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:#f044bc;\n"
"    border:none;\n"
"    border-radius: 4px;\n"
"    color:#FFFFFF;\n"
"    font-size: 18px;\n"
"}")
        self.gb_twofacauth.setTitle("")
        self.gb_twofacauth.setObjectName("gb_twofacauth")
        self.lb_name = QtWidgets.QLabel(parent=self.gb_twofacauth)
        self.lb_name.setGeometry(QtCore.QRect(160, 310, 290, 20))
        self.lb_name.setMinimumSize(QtCore.QSize(290, 0))
        self.lb_name.setMaximumSize(QtCore.QSize(290, 20))
        font = QtGui.QFont()
        font.setFamily("Inter Light")
        font.setPointSize(14)
        self.lb_name.setFont(font)
        self.lb_name.setStyleSheet("QLabel {\n"
"    color: #9095A0;\n"
"}")
        self.lb_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_name.setObjectName("lb_name")
        self.le_otp = QtWidgets.QLineEdit(parent=self.gb_twofacauth)
        self.le_otp.setGeometry(QtCore.QRect(50, 380, 506, 32))
        self.le_otp.setMinimumSize(QtCore.QSize(506, 0))
        self.le_otp.setMaximumSize(QtCore.QSize(516, 52))
        self.le_otp.setObjectName("le_otp")
        self.pb_otp = QtWidgets.QPushButton(parent=self.gb_twofacauth)
        self.pb_otp.setGeometry(QtCore.QRect(60, 460, 482, 36))
        self.pb_otp.setMaximumSize(QtCore.QSize(482, 36))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        self.pb_otp.setFont(font)
        self.pb_otp.setObjectName("pb_otp")
        self.groupBox = QtWidgets.QGroupBox(parent=self.gb_twofacauth)
        self.groupBox.setGeometry(QtCore.QRect(110, 40, 380, 269))
        self.groupBox.setMaximumSize(QtCore.QSize(381, 269))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 301, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/logo_u2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 210, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(36)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #323842;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.gb_container)
        self.label_3.setGeometry(QtCore.QRect(940, 550, 471, 371))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/otp_elements/Image 50.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.gb_container)
        self.label_4.setGeometry(QtCore.QRect(370, 260, 661, 691))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/otp_elements/Image 51-1.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.gb_container)
        self.label_5.setGeometry(QtCore.QRect(910, 140, 601, 501))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/otp_elements/Image 51.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.gb_twofacauth.raise_()

        self.retranslateUi(OTP)
        QtCore.QMetaObject.connectSlotsByName(OTP)

    def retranslateUi(self, OTP):
        _translate = QtCore.QCoreApplication.translate
        OTP.setWindowTitle(_translate("OTP", "Form"))
        self.lb_name.setText(_translate("OTP", "Enter your code to verify it\'s you"))
        self.pb_otp.setText(_translate("OTP", "Submit"))
        self.label.setText(_translate("OTP", "Enter OTP Code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OTP = QtWidgets.QWidget()
    ui = Ui_OTP()
    ui.setupUi(OTP)
    OTP.show()
    sys.exit(app.exec())
