# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\src\ui/loginForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 400))
        self.gb_login = QtWidgets.QGroupBox(parent=Form)
        self.gb_login.setGeometry(QtCore.QRect(960, 0, 960, 1080))
        self.gb_login.setMinimumSize(QtCore.QSize(720, 0))
        self.gb_login.setTitle("")
        self.gb_login.setObjectName("gb_login")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.gb_login)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 320, 581, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.fl_login = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.fl_login.setContentsMargins(0, 0, 0, 0)
        self.fl_login.setObjectName("fl_login")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.fl_login.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.le_username = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.le_username.setObjectName("le_username")
        self.fl_login.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_username)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.fl_login.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.le_pass = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.le_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_pass.setObjectName("le_pass")
        self.fl_login.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_pass)
        self.pb_logIn = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.pb_logIn.setObjectName("pb_logIn")
        self.fl_login.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pb_logIn)
        self.gb_banner = QtWidgets.QGroupBox(parent=Form)
        self.gb_banner.setGeometry(QtCore.QRect(0, 0, 961, 1081))
        self.gb_banner.setTitle("")
        self.gb_banner.setObjectName("gb_banner")
        self.label_3 = QtWidgets.QLabel(parent=self.gb_banner)
        self.label_3.setGeometry(QtCore.QRect(220, 280, 391, 221))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(26)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_username, self.le_pass)
        Form.setTabOrder(self.le_pass, self.pb_logIn)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Username:"))
        self.label_2.setText(_translate("Form", "Password:"))
        self.pb_logIn.setText(_translate("Form", "Login"))
        self.label_3.setText(_translate("Form", "BENEFICIARY STORE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
