# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\src\ui/OTP.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OTP(object):
    def setupUi(self, OTP):
        OTP.setObjectName("OTP")
        OTP.resize(1920, 1080)
        self.gb_twofacauth = QtWidgets.QGroupBox(parent=OTP)
        self.gb_twofacauth.setGeometry(QtCore.QRect(500, 320, 581, 341))
        self.gb_twofacauth.setTitle("")
        self.gb_twofacauth.setObjectName("gb_twofacauth")
        self.lb_name = QtWidgets.QLabel(parent=self.gb_twofacauth)
        self.lb_name.setGeometry(QtCore.QRect(190, 100, 211, 16))
        self.lb_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_name.setObjectName("lb_name")
        self.layoutWidget = QtWidgets.QWidget(parent=self.gb_twofacauth)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 170, 581, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.le_otp = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.le_otp.setObjectName("le_otp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_otp)
        self.pb_otp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_otp.setObjectName("pb_otp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pb_otp)

        self.retranslateUi(OTP)
        QtCore.QMetaObject.connectSlotsByName(OTP)

    def retranslateUi(self, OTP):
        _translate = QtCore.QCoreApplication.translate
        OTP.setWindowTitle(_translate("OTP", "Form"))
        self.lb_name.setText(_translate("OTP", "PlaceHolder"))
        self.label_4.setText(_translate("OTP", "OTP"))
        self.pb_otp.setText(_translate("OTP", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OTP = QtWidgets.QWidget()
    ui = Ui_OTP()
    ui.setupUi(OTP)
    OTP.show()
    sys.exit(app.exec())
