# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/ActivityLogs.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_activity_logs(object):
    def setupUi(self, activity_logs):
        activity_logs.setObjectName("activity_logs")
        activity_logs.resize(1600, 1030)
        activity_logs.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        activity_logs.setAutoFillBackground(False)
        activity_logs.setStyleSheet("QWidget#cashier_dashboard {\n"
"    background: #FFFFFF;\n"
"}")
        self.gb_container = QtWidgets.QGroupBox(parent=activity_logs)
        self.gb_container.setGeometry(QtCore.QRect(459, 40, 1131, 900))
        self.gb_container.setStyleSheet("QGroupBox {\n"
"    background: rgba(248,249,250, 1);\n"
"    border: 3px solid rgba(29,33,40, 1);\n"
"    border-radius:13px;\n"
"}")
        self.gb_container.setTitle("")
        self.gb_container.setObjectName("gb_container")
        self.tw_actvitylogs = QtWidgets.QTabWidget(parent=self.gb_container)
        self.tw_actvitylogs.setGeometry(QtCore.QRect(10, 10, 1111, 881))
        self.tw_actvitylogs.setObjectName("tw_actvitylogs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lb_logs = QtWidgets.QLabel(parent=self.tab)
        self.lb_logs.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(24)
        font.setBold(True)
        self.lb_logs.setFont(font)
        self.lb_logs.setObjectName("lb_logs")
        self.le_sort = QtWidgets.QLineEdit(parent=self.tab)
        self.le_sort.setGeometry(QtCore.QRect(260, 10, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.le_sort.setFont(font)
        self.le_sort.setStyleSheet("QLineEdit {\n"
"    background: rgba(255,255,255,1); /* white */\n"
"  border-radius: 20px; \n"
"  border-width: 3px; \n"
"  border-color: rgba(29,33,40,1); /* neutral-800 */\n"
"  border-style: solid; \n"
"}")
        self.le_sort.setText("")
        self.le_sort.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.le_sort.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
        self.le_sort.setObjectName("le_sort")
        self.tv_activity_logs = QtWidgets.QTableView(parent=self.tab)
        self.tv_activity_logs.setGeometry(QtCore.QRect(10, 60, 1081, 791))
        self.tv_activity_logs.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tv_activity_logs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tv_activity_logs.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.tv_activity_logs.setAlternatingRowColors(False)
        self.tv_activity_logs.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tv_activity_logs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tv_activity_logs.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.tv_activity_logs.setShowGrid(False)
        self.tv_activity_logs.setSortingEnabled(True)
        self.tv_activity_logs.setObjectName("tv_activity_logs")
        self.tv_activity_logs.horizontalHeader().setDefaultSectionSize(300)
        self.tv_activity_logs.horizontalHeader().setMinimumSectionSize(0)
        self.tw_actvitylogs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tw_actvitylogs.addTab(self.tab_2, "")
        self.gb_logdetails = QtWidgets.QGroupBox(parent=activity_logs)
        self.gb_logdetails.setGeometry(QtCore.QRect(20, 250, 421, 541))
        self.gb_logdetails.setTitle("")
        self.gb_logdetails.setObjectName("gb_logdetails")
        self.lb_logs_2 = QtWidgets.QLabel(parent=self.gb_logdetails)
        self.lb_logs_2.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        font.setBold(True)
        self.lb_logs_2.setFont(font)
        self.lb_logs_2.setObjectName("lb_logs_2")

        self.retranslateUi(activity_logs)
        self.tw_actvitylogs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(activity_logs)

    def retranslateUi(self, activity_logs):
        _translate = QtCore.QCoreApplication.translate
        activity_logs.setWindowTitle(_translate("activity_logs", "Form"))
        self.lb_logs.setText(_translate("activity_logs", "Activity Logs"))
        self.le_sort.setPlaceholderText(_translate("activity_logs", "Search Here"))
        self.tw_actvitylogs.setTabText(self.tw_actvitylogs.indexOf(self.tab), _translate("activity_logs", "Tab 1"))
        self.tw_actvitylogs.setTabText(self.tw_actvitylogs.indexOf(self.tab_2), _translate("activity_logs", "Tab 2"))
        self.lb_logs_2.setText(_translate("activity_logs", "Log Details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    activity_logs = QtWidgets.QWidget()
    ui = Ui_activity_logs()
    ui.setupUi(activity_logs)
    activity_logs.show()
    sys.exit(app.exec())
