# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/CustomCashierItems.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cashier_item(object):
    def setupUi(self, cashier_item):
        cashier_item.setObjectName("cashier_item")
        cashier_item.resize(1000, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(cashier_item.sizePolicy().hasHeightForWidth())
        cashier_item.setSizePolicy(sizePolicy)
        cashier_item.setMinimumSize(QtCore.QSize(1000, 0))
        self.lb_image = QtWidgets.QLabel(parent=cashier_item)
        self.lb_image.setGeometry(QtCore.QRect(0, 0, 150, 150))
        self.lb_image.setText("")
        self.lb_image.setPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/default.jpg"))
        self.lb_image.setScaledContents(True)
        self.lb_image.setObjectName("lb_image")
        self.lb_name = QtWidgets.QLabel(parent=cashier_item)
        self.lb_name.setGeometry(QtCore.QRect(150, 0, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Inter Black")
        font.setPointSize(28)
        font.setBold(True)
        self.lb_name.setFont(font)
        self.lb_name.setObjectName("lb_name")
        self.lb_description = QtWidgets.QLabel(parent=cashier_item)
        self.lb_description.setGeometry(QtCore.QRect(150, 50, 321, 41))
        self.lb_description.setObjectName("lb_description")
        self.pb_del = QtWidgets.QPushButton(parent=cashier_item)
        self.pb_del.setGeometry(QtCore.QRect(860, 100, 141, 51))
        self.pb_del.setObjectName("pb_del")
        self.sb_quantity = QtWidgets.QSpinBox(parent=cashier_item)
        self.sb_quantity.setGeometry(QtCore.QRect(240, 120, 61, 31))
        self.sb_quantity.setObjectName("sb_quantity")
        self.label = QtWidgets.QLabel(parent=cashier_item)
        self.label.setGeometry(QtCore.QRect(180, 120, 61, 21))
        self.label.setObjectName("label")
        self.lb_price = QtWidgets.QLabel(parent=cashier_item)
        self.lb_price.setGeometry(QtCore.QRect(868, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.lb_price.setFont(font)
        self.lb_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_price.setObjectName("lb_price")

        self.retranslateUi(cashier_item)
        QtCore.QMetaObject.connectSlotsByName(cashier_item)

    def retranslateUi(self, cashier_item):
        _translate = QtCore.QCoreApplication.translate
        cashier_item.setWindowTitle(_translate("cashier_item", "Form"))
        self.lb_name.setText(_translate("cashier_item", "PRODUCT NAME"))
        self.lb_description.setText(_translate("cashier_item", "SHORT DESCRIPTION: LOREM "))
        self.pb_del.setText(_translate("cashier_item", "VOID ITEM"))
        self.label.setText(_translate("cashier_item", "Quantity:"))
        self.lb_price.setText(_translate("cashier_item", "Price"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cashier_item = QtWidgets.QWidget()
    ui = Ui_cashier_item()
    ui.setupUi(cashier_item)
    cashier_item.show()
    sys.exit(app.exec())
