# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/CustomMessageBox.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_custom_modal(object):
    def setupUi(self, custom_modal):
        custom_modal.setObjectName("custom_modal")
        custom_modal.resize(503, 565)
        custom_modal.setStyleSheet("QWidget#custom_modal {\n"
"    background-color: #FFFFFF;\n"
"    border: 4px solid #FF7FDF;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius:5px;\n"
"    border: 1px solid #5E5E5E;\n"
"    padding: 5px 5px;\n"
"}")
        self.pb_close = QtWidgets.QPushButton(parent=custom_modal)
        self.pb_close.setGeometry(QtCore.QRect(450, 10, 30, 30))
        self.pb_close.setStyleSheet("QPushButton {\n"
"    background: #00000000;\n"
"    border: none;\n"
"}")
        self.pb_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\abarq\\PycharmProjects\\POS-PY\\ui\\../src/frontend/__image/circle-xmark.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pb_close.setIcon(icon)
        self.pb_close.setIconSize(QtCore.QSize(30, 30))
        self.pb_close.setObjectName("pb_close")
        self.layoutWidget = QtWidgets.QWidget(parent=custom_modal)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 470, 501, 40))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hl_confirm = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hl_confirm.setContentsMargins(0, 0, 0, 0)
        self.hl_confirm.setObjectName("hl_confirm")
        self.pb_yes = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_yes.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.pb_yes.setFont(font)
        self.pb_yes.setObjectName("pb_yes")
        self.hl_confirm.addWidget(self.pb_yes)
        self.pb_no = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_no.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.pb_no.setFont(font)
        self.pb_no.setStyleSheet("QPushButton {\n"
"    background-color: #cc0000;\n"
"    color: #FEFEFE;\n"
"}")
        self.pb_no.setObjectName("pb_no")
        self.hl_confirm.addWidget(self.pb_no)
        self.layoutWidget1 = QtWidgets.QWidget(parent=custom_modal)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 20, 421, 451))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.vl_elements = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.vl_elements.setContentsMargins(0, 0, 0, 0)
        self.vl_elements.setObjectName("vl_elements")
        self.lb_message = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lb_message.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(False)
        self.lb_message.setFont(font)
        self.lb_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_message.setObjectName("lb_message")
        self.vl_elements.addWidget(self.lb_message)
        self.lb_element = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lb_element.setMinimumSize(QtCore.QSize(300, 300))
        self.lb_element.setMaximumSize(QtCore.QSize(421, 421))
        self.lb_element.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_element.setObjectName("lb_element")
        self.vl_elements.addWidget(self.lb_element)
        self.lb_title = QtWidgets.QLabel(parent=custom_modal)
        self.lb_title.setGeometry(QtCore.QRect(20, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        self.lb_title.setFont(font)
        self.lb_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lb_title.setObjectName("lb_title")
        self.layoutWidget2 = QtWidgets.QWidget(parent=custom_modal)
        self.layoutWidget2.setGeometry(QtCore.QRect(90, 90, 321, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_choice_4 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pb_choice_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.pb_choice_4.setFont(font)
        self.pb_choice_4.setObjectName("pb_choice_4")
        self.gridLayout.addWidget(self.pb_choice_4, 0, 0, 1, 1)
        self.pb_choice_3 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pb_choice_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.pb_choice_3.setFont(font)
        self.pb_choice_3.setObjectName("pb_choice_3")
        self.gridLayout.addWidget(self.pb_choice_3, 0, 1, 1, 1)
        self.pb_choice_2 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pb_choice_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.pb_choice_2.setFont(font)
        self.pb_choice_2.setObjectName("pb_choice_2")
        self.gridLayout.addWidget(self.pb_choice_2, 1, 0, 1, 1)
        self.pb_choice_1 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pb_choice_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.pb_choice_1.setFont(font)
        self.pb_choice_1.setObjectName("pb_choice_1")
        self.gridLayout.addWidget(self.pb_choice_1, 1, 1, 1, 1)

        self.retranslateUi(custom_modal)
        QtCore.QMetaObject.connectSlotsByName(custom_modal)

    def retranslateUi(self, custom_modal):
        _translate = QtCore.QCoreApplication.translate
        custom_modal.setWindowTitle(_translate("custom_modal", "Form"))
        self.pb_yes.setText(_translate("custom_modal", "Yes"))
        self.pb_no.setText(_translate("custom_modal", "No"))
        self.lb_message.setText(_translate("custom_modal", "Placeholder"))
        self.lb_element.setText(_translate("custom_modal", "PLACEHOLDER"))
        self.lb_title.setText(_translate("custom_modal", "Title"))
        self.pb_choice_4.setText(_translate("custom_modal", "Yes"))
        self.pb_choice_3.setText(_translate("custom_modal", "Yes"))
        self.pb_choice_2.setText(_translate("custom_modal", "Yes"))
        self.pb_choice_1.setText(_translate("custom_modal", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    custom_modal = QtWidgets.QWidget()
    ui = Ui_custom_modal()
    ui.setupUi(custom_modal)
    custom_modal.show()
    sys.exit(app.exec())
