# Form implementation generated from reading ui file 'C:\Users\abarq\PycharmProjects\POS-PY\ui/userInfoWidget.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(210, 306)
        self.pb_logout = QtWidgets.QPushButton(parent=Form)
        self.pb_logout.setGeometry(QtCore.QRect(0, 270, 121, 31))
        self.pb_logout.setStyleSheet("QPushButton {\n"
"    background: rgba(0,0,0,0);\n"
"    border: 1px solid rgba(0,0,0,0);\n"
"    border-radius: 37px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/frontend/__image/login_elements/sign-out-alt.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pb_logout.setIcon(icon)
        self.pb_logout.setIconSize(QtCore.QSize(24, 24))
        self.pb_logout.setObjectName("pb_logout")
        self.lb_username = QtWidgets.QLabel(parent=Form)
        self.lb_username.setGeometry(QtCore.QRect(0, 200, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(True)
        self.lb_username.setFont(font)
        self.lb_username.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lb_username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_username.setWordWrap(False)
        self.lb_username.setObjectName("lb_username")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 151, 171))
        self.groupBox.setStyleSheet("border: none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lb_userImage = QtWidgets.QLabel(parent=self.groupBox)
        self.lb_userImage.setGeometry(QtCore.QRect(0, 0, 150, 150))
        self.lb_userImage.setStyleSheet("QLabel {\n"
"    border-radius: 48px;\n"
"}")
        self.lb_userImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_userImage.setObjectName("lb_userImage")
        self.lb_role = QtWidgets.QLabel(parent=Form)
        self.lb_role.setGeometry(QtCore.QRect(0, 220, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setUnderline(True)
        self.lb_role.setFont(font)
        self.lb_role.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lb_role.setStyleSheet("QLabel {\n"
"    color:  rgba(232,69,191,1);\n"
"}")
        self.lb_role.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_role.setWordWrap(False)
        self.lb_role.setObjectName("lb_role")
        self.pb_setImage = QtWidgets.QPushButton(parent=Form)
        self.pb_setImage.setGeometry(QtCore.QRect(90, 163, 31, 31))
        self.pb_setImage.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 15px;\n"
"}")
        self.pb_setImage.setObjectName("pb_setImage")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_logout.setText(_translate("Form", "Log out"))
        self.lb_username.setText(_translate("Form", "Name"))
        self.lb_userImage.setText(_translate("Form", "IMAGE PLACE HOLDER"))
        self.lb_role.setText(_translate("Form", "Roles"))
        self.pb_setImage.setText(_translate("Form", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
