# Form implementation generated from reading ui file 'C:/Users/abarq/PycharmProjects/POS-PY/src/ui/userInfoWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(210, 310)
        self.pb_logout = QtWidgets.QPushButton(parent=Form)
        self.pb_logout.setGeometry(QtCore.QRect(70, 260, 75, 24))
        self.pb_logout.setObjectName("pb_logout")
        self.lb_username = QtWidgets.QLabel(parent=Form)
        self.lb_username.setGeometry(QtCore.QRect(0, 200, 211, 20))
        self.lb_username.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lb_username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_username.setWordWrap(False)
        self.lb_username.setObjectName("lb_username")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 151, 171))
        self.groupBox.setStyleSheet("border: none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lb_userImage = QtWidgets.QLabel(parent=self.groupBox)
        self.lb_userImage.setGeometry(QtCore.QRect(0, 0, 150, 150))
        self.lb_userImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_userImage.setObjectName("lb_userImage")
        self.pb_setImage = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_setImage.setGeometry(QtCore.QRect(40, 130, 75, 24))
        self.pb_setImage.setObjectName("pb_setImage")
        self.lb_role = QtWidgets.QLabel(parent=Form)
        self.lb_role.setGeometry(QtCore.QRect(0, 220, 211, 20))
        self.lb_role.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lb_role.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_role.setWordWrap(False)
        self.lb_role.setObjectName("lb_role")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_logout.setText(_translate("Form", "Log out"))
        self.lb_username.setText(_translate("Form", "Name"))
        self.lb_userImage.setText(_translate("Form", "IMAGE PLACE HOLDER"))
        self.pb_setImage.setText(_translate("Form", "Set"))
        self.lb_role.setText(_translate("Form", "Roles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
